spring:
  cloud:
    azure:
      servicebus:
        namespace: shaik-exchanges
        entity-type: queue
    credential:
      managed-identity-enabled: true
    keyvault:
      secret:
        endpoint: https://shaik-exchange-key-valut.vault.azure.net/
